### ISSUE TITLE
assertNever without throwing an exception

### ISSUE THREAD

**Issue by hoeck** [aikoven/assert-never#1]
First of all, thanks for wrapping up this TS pattern as an NPM-module, just learned about that TS feature recently while skimming the docs for sth. completely different :D.

I was about to include it but found that sth. is missing:

When dispatching redux actions in switch-case statements, I want to get a compiler error when I forget to dispatch an action but I don't want to throw an exception at runtime. This is bc. the default redux reducer combinator is sending actions to all reducers and expects them to do nothing if they don't know the action.

So, it would be useful to have a `assertNeverSilently` or `assertNeverAndIgnore` or similar function that is just defined as:

```
function assertNeverAndIgnore (x: never): never {
    return x
}
```

If you could include this (or accept a PR) that would be nice.

**Comment by aikoven** [comment]
How about this:
```ts
function assertNever(value: never, noThrow = false): never
```

I'd be happy to accept a PR :)

**Comment by hoeck** [comment]
That: `function assertNever(value: never, noThrow = false): never` sounds great, hadn't thought of overloading at all. I'm going to provide you with a PR.
