### ISSUE TITLE
index.d.ts missing from the node_modules/assert-never folder

### ISSUE THREAD

**Issue by bartocc** [aikoven/assert-never#4]
The file `index.d.ts`, referenced in `package.json` with `"typings": "index.d.ts",` is not present in my project's `node_modules/assert-never` folder.

I've seen the `prepublish` script in `package.json` that should run the `build` script when publishing, but something might have gone wrong when 1.2.0 was published.

Or maybe this is normal and I miss some rationale here 🤗

**Comment by aikoven** [comment]
You're right, for some reason, NPM doesn't include `index.d.ts` file, although it does include `index.ts`. I added `files` section to `package.json` and published version `1.2.1`.

**Comment by bartocc** [comment]
Great ! Thx
