### ISSUE TITLE
Rollup packaging error, how to handle it

### ISSUE THREAD

**Issue by parlay96** [aikoven/assert-never#5]
![image](https://github.com/aikoven/assert-never/assets/32978177/2beead2e-972d-4f68-9800-102d5b2147d5)

**Comment by aikoven** [comment]
For some reason rollup is trying to import `.ts` file. But the `package.json` has `"main": "index.js"`. It seems to be a problem with your configuration.

**Comment by parlay96** [comment]
Do you know what the problem is

**Comment by aikoven** [comment]
No, I don't use Rollup

**Comment by parlay96** [comment]
thank you still
