### ISSUE TITLE
Allow optionally providing the error message to use

### ISSUE THREAD

**Issue by codeandcats** [aikoven/assert-never#6]
Thanks for an awesome function, I've been happily using it for years in many projects.

I've often wished though that I could specify the error message to use, as the default error message can be a little abstract, especially if it surfaces to an end user in any way, like in a public API.

It would be nice if had the following overloads:

```ts
export function assertNever(value: never, noThrow?: boolean): never

export function assertNever(value: never, errorMessage?: string): never

export function assertNever(value: never, getErrorMessage?: (value: unknown) => string): never
```

This way, in addition to it's current usage, it could be called like this (contrived example):

```ts
assertNever(paymentType, 'Invalid payment type')
```

Or

```ts
assertNever(paymentType, value => `Invalid payment type: ${String(value)}`)
```

If you are open to the idea, I have already taken the liberty of opening a [PR](https://github.com/aikoven/assert-never/pull/7). Thank you.

**Comment by aikoven** [comment]
Hey @codeandcats!

I think that this is a great addition! Your proposed API even allows to throw a custom error by throwing it from the `getErrorMessage` callback.

I am going to merge your PR and publish a release shortly.
